### DISCUSSION TITLE
Interpolating messages

### DISCUSSION THREAD

**Discussion by jmle** [konveyor/analyzer-lsp#452] [General]
Currently, for rules with custom variables like the following
```yaml
- category: mandatory
  customVariables:
  - name: renamed
    nameOfCaptureGroup: renamed
    pattern: javax.(?P<renamed>(activation|annotation|batch|decorator|ejb|el|enterprise|faces|inject|interceptor|jms|json|jws|mail|persistence|resource|security|servlet|transaction|validation|websocket|ws|xml))?.*
  description: javax.{renamed} has been replaced by jakarta.{renamed}
  effort: 1
  labels:
  - konveyor.io/target=jakarta-ee9+
  - ...
  message: 'Replace the `javax.{{renamed}}` import statement with `jakarta.{{renamed}}`
  ruleID: javax-to-jakarta-import-00001
  when:
    as: javaClass
    java.referenced:
      location: IMPORT
      pattern: javax.(activation|annotation|batch|decorator|ejb|el|enterprise|faces|inject|interceptor|jms|json|jws|mail|persistence|resource|security|servlet|transaction|validation|websocket|ws|xml)*
```
we interpolate the `message` field only in the incidents shown in the snippets. This makes sense, since we bundle all the different incidents, with the different matches (and therefore potential interpolable variables) in a single issue.

As a consequence, there is no single way of interpolating the `message` field for it to be shown when the issue is opened (see screenshot, right below rule id), since there are multiple possibilities. ![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/79fcb2b0-b482-4868-aa15-5aa3c14dd2d6)

A possible solution could be to interpolate the general message for the issue with _all the different matches found_, or'ing them:
> `javax.(jms|mail|ejb)` has been replaced by `jakarta.(jms|mail|ejb)`

Another possibility is to have an additional, modified message field for showing in the description, which wouldn't have any
template for interpolation, although this would require extensive modification of the rulesets.

What do you think?
