### ISSUE TITLE
Mistake in rule-example?:  apiextensions/v1beta1/customresourcedefinitions is deprecated, apiextensions/v1/customresourcedefinitions should be used instead

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/analyzer-lsp#110]
Think we might have a mistake with the below example on line 35

https://github.com/konveyor/analyzer-lsp/blob/main/rule-example.yaml#L35

```
- message: apiextensions/v1beta1/customresourcedefinitions is deprecated, apiextensions/v1/customresourcedefinitions should be used instead
  ruleID: lang-ref-001
  when:
    or:
    - java.referenced:
        pattern: "*CustomResourceDefinition*"
        location: TYPE
    - go.referenced: "*CustomResourceDefinition*"
```

Assume this will match for all uses of CustomResourceDefinition, not just the apiextensions/v1beta1 the message states?
