### ISSUE TITLE
Change dependency output into a list by provider

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#140]
Right now, the dependencies from all providers are output in the same list or tree. 

For instance, if `java` provider provides `dep2` and `dep3`, while the `go` provider gives `dep1`. The current output looks like:

```yaml
- dep1
- dep2
- dep3
```  

We should separate them by providers like so: 

```yaml
- provider: java
  dependencies:
  - dep2
  - dep3
- provider: golang
  dependencies:
  - dep1
```

This will also help populate the language field in the UI
