### ISSUE TITLE
Support templating in tags

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#181]
Tags should be able to use templates

**Comment by shawn-hurley** [comment]
Can you give an example of a use case?

**Comment by pranavgaikwad** [comment]
@shawn-hurley Lets say I am writing a rule to tag an application based on contents of the LICENSE file, it'd be easier to just do: 

```
when:
  or:
    builtin.filecontent: "Apache 1.0"
    builtin.filecontent: "Apache 1.1"
    builtin.filecontent: "BSD" 
tag: "{{ match }}"
```

Right now, I will have to write 3 different rules to achieve above.
