### ISSUE TITLE
METHOD_CALL location not working

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#223]
See for instance [this test failure](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A74). 

Also tested using the following:
```yaml
    java.referenced:
      location: METHOD_CALL
      pattern: java.lang.System.getenv()
```
on
```java
public class Main {
    public static void main(String[] args) {
        System.getenv();
    }
}
```
and also
```yaml
    java.referenced:
      location: METHOD_CALL
      pattern: java.lang.String.length()
```
on
```java
public class Main {
    public static void main(String[] args) {
        String hey = "hey";
        hey.length();
    }
}
```
