### ISSUE TITLE
Captured group does not appear in message

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#224]
The captured group is not being interpolated in the rule message:
```yaml
- customVariables:
  - name: renamed
    nameOfCaptureGroup: renamed
    pattern: ...
```
with
```yaml
  message: Replace the `javax.{{renamed}}` import statement with `jakarta.{{renamed}}`
```
appears as
```yaml
       message: Replace the `javax.` import statement with `jakarta.`
```

See for instance [this failing test](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A289).
