### ISSUE TITLE
When grep exits without errors but there are no matches, the provider reports it as an error

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#283]
To reproduce, run the following rule against customer tomcat example app:

```
- category: mandatory
  customVariables: []
  description: |-
   Test rule.
  effort: 1
  message: test-message
  ruleID: test-rule
  when:
    builtin.filecontent:
      pattern: <%
```
