### ISSUE TITLE
When all dependency conditions are filtered out, engine returns an error for AND/OR conditions that only had dep conditions as children

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#289]
When using `--no-dependency-rules` option, it might happen that we filter out all conditions in AND / OR making the rule fail with `conditions must not be empty while evaluating` originating from https://github.com/konveyor/analyzer-lsp/blob/c845b6a573897a0cba36b598131b20760aafa5f0/engine/conditions.go#L147

Run following rule with example apps to reproduce: 

```yaml
- category: potential
  customVariables: []
  description: |-
    Artemis JMS Client requires wildfly-client-properties
    If you migrate your application to JBoss EAP 7.3 (or later), and want to ensure its Maven building, running or testing works as expected, if the application depends on Artemis JMS Client artifact then it should also depend on artifact with groupId `org.jboss.eap`, and artifactId `wildfly-client-properties`.
  effort: 1
  tag:
  - test
  labels:
  - konveyor.io/target=eap7
  - konveyor.io/source
  - jms
  - JMS
  ruleID: maven-artemis-jms-client-00001
  when:
    or:
    - and:
      - java.dependency:
          lowerbound: 0.0.0
          name: org.apache.activemq.artemis-jms-client
````

We probably need to make this error non-fatal. This is because the rule evaluation doesn't really result in fatal error when there are no conditions.
