### ISSUE TITLE
Incidents for the "JBoss API reference " issue not found in neither application source nor dependencies

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#329]
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration:
  - Source + Dependencies
  - eap6
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

The _JBoss API reference_ issue is not generating incidents when analyzing the tackle-testapp application, neither in its source code nor the associated dependencies, when it should be found in both.

### How to reproduce

- Analyze tackle-test app with the configuration available in the Environment section.
- Go to the issues view, Single application and filter by the tackle-testapp application.

### Expected result

The _JBoss API reference_ issue should appear in the list of issues for the application. Windup analysis reports 3671 incidents in the dependencies and 6 incidents in the application source:

![Screenshot from 2023-09-12 11-54-28](https://github.com/konveyor/analyzer-lsp/assets/15966456/db9469ee-7bf4-4a84-970f-5b45b9e7a116)

![Screenshot from 2023-09-12 11-54-38](https://github.com/konveyor/analyzer-lsp/assets/15966456/bf08d49d-162b-4c44-8e81-b2234bf4de19)

### Actual result

The _JBoss API reference_ issue doesn't appear in the list of issues for the tackle-testapp application.

**Comment by pranavgaikwad** [comment]
@shawn-hurley I think this is related to package search thing. Here's the rule that's expected to be triggered:

```
- category: potential
  customVariables:
  - name: type
    nameOfCaptureGroup: type
    pattern: org.(?P<subpackage>(jboss|jbpm).)?(?P<package-remainder>([a-z]+\.)*)?(?P<type>[^.()]+)?
  - name: subpackage
    nameOfCaptureGroup: subpackage
    pattern: org.(?P<subpackage>(jboss|jbpm).)?(?P<package-remainder>([a-z]+\.)*)?(?P<type>[^.()]+)?
  - name: package-remainder
    nameOfCaptureGroup: package-remainder
    pattern: org.(?P<subpackage>(jboss|jbpm).)?(?P<package-remainder>([a-z]+\.)*)?(?P<type>[^.()]+)?
  description: |
    JBoss API reference
  effort: 0
  labels:
  - konveyor.io/source=java
  - konveyor.io/source=javaee
  - konveyor.io/source=soa
  - konveyor.io/target=eap6
  - phase=PostMigrationRulesPhase
  - catchall
  - jboss
  links: []
  message: '`org.{{subpackage}}.{{package-remainder}}{{type}}` reference found. No
    specific details available.'
  ruleID: generic-catchall-00700
  when:
    java.referenced:
      pattern: org.(jboss|jbpm).([a-z]+.)*[^.()]+
```
