### ISSUE TITLE
[BUG] Dep label selector should not be applied on issues coming from a dependency condition

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

release-0.3, beta.1

### Priority

Critical

### Current Behavior

We filter out the issue when it comes from a dependency that's open source. To fix this, we should remove https://github.com/konveyor/analyzer-lsp/blob/f3e52e0a68ac150d87748e52244757fe39f2ec48/provider/provider.go#L553-L560

### Expected Behavior

We shouldn't filter out an issue when the condition is looking for an open source dependency. This is because the incident doesn't itself come from a dependency. It is just an indication that the dependency exists. 

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Install konveyor latest, alpha.6 or beta.1
2. Set up [book-server](https://github.com/ibraginsky/book-server) app 
3. Select quarkus target for analysis
4. `springboot-web-to-quarkus-00000` rule should be matched. 

### Environment

```markdown
- **Analyzer Image SHA** latest
- **JDTLS  base image SHA** latest
- **Provider Settings JSON**
```

### Anything else?

To reproduce this bug standalone, clone [book-server](https://github.com/ibraginsky/book-server) app. Set up provider config with location pointing to this app. And run against following rule:

```yaml
- category: mandatory
  customVariables: []
  description: |-
    Replace the Spring Web artifact with Quarkus 'spring-web' extension
    Replace the Spring Web artifact with Quarkus `spring-web` extension. Spring Web is a spring-web artifact brought transitively by any `org.springframework:spring-web*` dependency. Add Quarkus dependency `io.quarkus:quarkus-spring-web`. Starting with Quarkus version 2.5, the underlying JAX-RS engine must be chosen. For performance reasons,. the `quarkus-resteasy-reactive-jackson` dependency should be used.
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=quarkus
  links:
  - title: Quarkus Spring Web Guide
    url: https://quarkus.io/guides/spring-web
  - title: Quarkus Migration Guide 2.5
    url: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.5#spring-web
  message: Replace the Spring Web artifact with Quarkus `spring-web` extension. Spring
    Web is a spring-web artifact brought transitively by any `org.springframework:spring-web*`
    dependency. Add Quarkus dependency `io.quarkus:quarkus-spring-web`. Starting with
    Quarkus version 2.5, the underlying JAX-RS engine must be chosen. For performance
    reasons,. the `quarkus-resteasy-reactive-jackson` dependency should be used.
  ruleID: springboot-web-to-quarkus-00000
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.spring-web
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.boot.spring-boot-starter-web
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.spring-web
```
