### ISSUE TITLE
Add ability to include / exclude incidents based on package / modules / assembly

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#432]
Add ability to include / exclude incidents based on which package they come from. The business logic of inclusion / exclusion will change from provider to provider. 

In general, here are the four scenarios describing how it will work:

### Scenario 1: Only Include Set

```yaml
Include:
- org.apache.*
Exclude: null
```

_Filter-in_ incidents in packages matching `org.apache.*` pattern. 
_Filter-out_ everything else.

### Scenario 2: Only Exclude Set

```yaml
Include: null
Exclude:
- org.apache.*
```

_Filter-out_ incidents in packages matching `org.apache.*` pattern. 
_Filter-in_ everything else.

#### Case 1: Exclude is a subset of Include

```yaml
Include:
- org.apache.*
- io.konveyor.*
Exclude:
- org.apache.example.*
- io.konveyor.demo.*
```

_Filter-in_ incidents in packages matching `org.apache.*` OR `io.konveyor.*`. 
Among the filtered-in packages, _filter-out_ everything that further matches `org.apache.example.*` OR `io.konveyor.demo.*`.

#### Case 2: Include is a subset of Exclude

```yaml
Include:
- org.apache.example.*
- io.konveyor.demo.*
Exclude:
- org.apache.*
- io.konveyor.*
```

_Filter-in_ incidents in packages matching `org.apache.example.*` OR `io.konveyor.demo.*`. 
Among the filtered-in packages, _filter-out_ everything that further matches `org.apache.*` OR `io.konveyor.*`.

> The result of this specific operation will be 0 incidents.

### Scenario 4: Include / Exclude Set with exclusive packages
 
```yaml
Include:
- org.apache.*
Exclude:
- io.konveyor.*
```

_Filter-in_ incidents in packages matching `org.apache.*`.
Among the filtered-in packages, _filter-out_ everything that further matches `io.konveyor.*`

> Result of this operation will be equivalent to setting Exclude to null
