### ISSUE TITLE
Analysis fails with REGEX error.

### ISSUE THREAD

**Issue by jortel** [konveyor/analyzer-lsp#442]
Run with seeded EAP7 ruleset.
```
errors:
    - severity: Error
      description: '[Analyzer] eap7/websphere.eap6-08001: error parsing regexp: invalid or unsupported Perl syntax: `(?!`'
    - severity: Error
      description: '[Analyzer] eap7/websphere.eap6-08001: error parsing regexp: invalid or unsupported Perl syntax: `(?!`'
    - severity: Error
      description: '[Analyzer] eap7/websphere.eap6-08002: error parsing regexp: invalid or unsupported Perl syntax: `(?!`'
```
