### ISSUE TITLE
[RFE] Ability to match on methods/functions/constructors with particular argument types

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#467]
The analyzer should have the ability to match on methods, functions or constructors that are passed a specific argument type, for instance:
```yaml
java.referenced:
  location: CONSTRUCTOR
  pattern: java.lang.String\(java.lang.StringBuilder\)
```
would match on:
```java
StringBuilder arg = new StringBuilder("Hello World!")'
String str = new String(arg);
```
but not on:
```java
String arg = "Hello World!";
String str = new String(arg);
```

We could either escape the parenthesis of the method call, as done in the yaml example above, or add an additional field, as in:
```yaml
java.referenced:
  location: CONSTRUCTOR
  arguments:
    - java.lang.String
  pattern: java.lang.String(*)
```
