### ISSUE TITLE
[BUG] Conditions with location ANNOTATION and an asterisk are not matched

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0

### Priority

Critical

### Current Behavior

A condition like the following:
```yaml
  when:
    java.referenced:
      location: ANNOTATION
      pattern: javax.ejb*
```
or also
```yaml
  when:
    java.referenced:
      location: ANNOTATION
      pattern: javax.ejb.*
```
does not match.

### Expected Behavior

Condition should match.

### How Reproducible

Always (Default)

### Steps To Reproduce

Run the analyzer against a project with a matching annotation.
