### ISSUE TITLE
[BUG] Rule fails when analyzing OpenMRS app in full analysis mode

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.2, 0.4.0

### Priority

Critical

### Current Behavior

Running analysis on https://github.com/openmrs/openmrs-core app causes failure for following rule 

```yml
- message: | 
            OpenShift Container Platform: Understanding persistent storage
            An application running inside a container could lose access to
            a file in local storage. Recommendations The following recommendations
            depend on the function of the file in local storage: * Logging: Log to
            standard output and use a centralized log collector to analyze the logs.
            * Caching: Use a cache backing service. * Configuration: Store configuration
            settings in environment variables so that they can be updated without
            code changes. * Data storage: Use a database backing service for relational
            data or use a persistent data storage system. * Temporary data storage:
            Use the file system of a running container as a brief, single-transaction
            cache.
  ruleID: local-storage-00001
  when:
    or:
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.FileInputStream(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.FileWriter(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.FileReader(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.PrintStream(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.File(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.PrintWriter(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.io.RandomAccessFile(*)
    - java.referenced:
        location: CONSTRUCTOR_CALL
        pattern: java.util.zip.ZipFile(*)
    - java.referenced:
        location: METHOD_CALL
        pattern: java.io.File.createTempFile(*)
    - java.referenced:
        location: METHOD_CALL
        pattern: java.nio.file.Paths.get(*)
    - java.referenced:
        location: IMPORT
        pattern: org.springframework.web.bind.annotation.RestController
    - java.referenced:
        location: INHERITANCE
        pattern: org.springframework.data.repository.PagingAndSortingRepository
    - java.referenced:
        location: IMPLEMENTS_TYPE
        pattern: io.konveyor.demo.ordermanagement.service.ICustomerService
    - java.referenced:
        location: RETURN_TYPE
        pattern: io.konveyor.demo.ordermanagement.model.Customer*
    - java.referenced:
        location: VARIABLE_DECLARATION
        pattern: io.konveyor.demo.ordermanagement.model.Customer*
```

### Expected Behavior

The rule should not error.

### How Reproducible

Always (Default)

### Steps To Reproduce

Run analysis against OpenMRS app https://github.com/openmrs/openmrs-core with **full** analysis mode. 

Make sure you use release-0.3 or release-0.4 versions of the analyzer.

### Environment

```markdown
- **Analyzer Image SHA** release-0.3
- **JDTLS  base image SHA** release-0.3
- **Provider Settings JSON**
```
