### ISSUE TITLE
[BUG] Including Camel target in analysis of tackle-testapp-public causes other issues to disappear

### ISSUE THREAD

**Issue by mansam** [konveyor/analyzer-lsp#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5.0-beta.1

### Priority

Critical

### Current Behavior

Including the Camel target with any other combination of targets (including all of them) while running an analysis seems to cause no issues to be reported for an analysis that would otherwise report issues, with the exception of issues related to the Azure target. This is consistently reproducible. 

The analysis report includes the following error messages when the Camel target is included:

```yaml
errors:
    - severity: Error
      description: '[Analyzer] camel3/camel2.component-changes-00010: could not parse provided xpath query ''//*[c:crypto and not(b:crypto/@algorithm)]/c:crypto'': prefix b not defined.'
    - severity: Error
      description: '[Analyzer] camel3/camel2.component-changes-00010: could not parse provided xpath query ''//*[c:crypto and not(b:crypto/@algorithm)]/c:crypto'': prefix b not defined.'
    - severity: Error
      description: '[Analyzer] camel3/camel2.component-changes-00011: could not parse provided xpath query ''//*[c:secureXML and (count(c:secureXML/@passPhrase)+count(c:secureXML/@passPhraseByte))<1]/c:secureXML/'': expression must evaluate to a node-set'
```

### Expected Behavior

Adding more targets should not cause less issues to be reported.

### How Reproducible

Always (Default)

### Steps To Reproduce

Case 1:
1. Add tackle-testapp-public to application inventory.
2. Run analysis, selecting Quarkus target.
3. Observe that there are several Quarkus issues reported.

Case 2:
1. Add tackle-testapp-public to application inventory.
2. Run analysis, selecting Quarkus and Camel targets.
3. Observe that there are no issues reported.

Case 3:
1. Add tackle-testapp-public to application inventory.
2. Run analysis, selecting Quarkus, Camel and Azure targets.
3. Observe that there is one issue reported, related to the Azure target.

### Anything else?

[report.txt](https://github.com/user-attachments/files/16183312/report.txt)
