### ISSUE TITLE
[BUG] (METHOD|CONSTRUCTOR)_CALLs with arguments are not matched

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#781]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

0.6.0

### Priority

Critical

### Current Behavior

Currently, this condition
```yaml
    java.referenced:
      location: CONSTRUCTOR_CALL
      pattern: javax.servlet.UnavailableException(javax.servlet.Servlet,java.lang.String)
```
won't match against
```java
        String str = "something";
        Servlet s = exception1.getServlet();
        UnavailableException exception2 = new UnavailableException(s, str);
```
while according to [the JDTLS tools docs](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fsearch%2FSearchPattern.html) it should be a match.

Non FQN searches do not match either:
```yaml
    java.referenced:
      location: CONSTRUCTOR_CALL
      pattern: UnavailableException(Servlet,String)
```

### How Reproducible

Always (Default)

### Environment

```markdown
- **Analyzer Image SHA** 
- **JDTLS  base image SHA**
- **Provider Settings JSON**
```
